# Site settings
title: Email Conversion Tips & Tricks
header-img: img/home-bg.jpg
email: hello@clickhere.io
description: "Blog dedicated to tips and tricks for higher converting emails"
baseurl: ""
url: "http://blog.clickhere.io"
twitter_username: clickhereio
github_username:  clickhereio
facebook_username:  clickhereio

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:month:day/:title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
