# Site settings
title: ClickHere Blog
header-img: img/home-bg.jpg
email: hello@clickhere.io
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/"
url: "http://clickhereio.github.io"
twitter_username: clickhereio
github_username:  clickhereio
facebook_username:  clickhereio

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
