# Site settings
title: ClickHere Blog
header-img: img/clickhere.png
email: hello@clickhere.io
description: "Blog dedicated to tips and tricks for higher converting emails"
baseurl: "http://clickhereio.github.io"
url: "http://clickhereio.github.io"
twitter_username: clickhereio
github_username:  clickhereio
facebook_username:  clickhereio

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
